languageCode = "en-us"
title = "freakjoe.me"
baseurl = "http://freakjoe.me/"
theme = "beautifulhugo"

[Params]
	favicon = "favicon.ico"
	commit = false

[Author]
	name = "FreakJoe"
	email = "freakjoe@freakjoe.me"
	github = "FreakJoe"
	stackoverflow = "users/7396066/freakjoe"

[[menu.main]]
	name = "portfolio"
	weight = -100
	identifier = "portfolio"
	url = "/portfolio/"

[[menu.main]]
	name = "about"
	weight = -110
	identifier = "about"
	url = "/about/"

[[menu.main]]
	name = "blog"
	weight = -120
	identifier = "blog"
	url = "/"