languageCode = "en-us"
title = "freakjoe.me"
baseurl = "http://freakjoe.me/"
theme = "beautifulhugo"

[Params]
  favicon = "favicon.ico"
  commit = false

[Author]
  github = "FreakJoe"
  stackoverflow = "users/7396066/freakjoe"